FIX l10n_it_reverse_charge [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
FIX screenshots

FIX allow to use and compute RC field in invoice line form pop up

l10n_it_reverse_charge ADD "With additional supplier self invoice"
to enable the creation of an additional supplier self
invoice. This is tipically used for extraUE suppliers,
in order to show, in supplier register, an invoice to the
specified partner (tipically, my company), instead of the
extraUE partner

Also FIX
ValueError: "local variable 'tax_code_id' referenced before assignment" while evaluating
u'invoice_validate()'
when tax mapping not found